"""empty message

Revision ID: 133628a3aff
Revises: 18e9538995d
Create Date: 2014-04-18 21:45:57.759282

"""

# revision identifiers, used by Alembic.
revision = '133628a3aff'
down_revision = '18e9538995d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('max_played', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'max_played')
    ### end Alembic commands ###
